-- INSERTAR DATOS
    -- DATOS DE LA TABLA DE USUARIOS
    insert into proyectobox.usuarios (usuario,clave) values
    ('Betoloti', '1234'), ('Eduard', '2357'), ('Contraseña','contraseña'), ('Usuario', 'usuario');
    -- DATOS DE LA TABLA PAIS
    INSERT INTO proyectobox.paises () VALUES (1, 'AF', 'Afganistán'),
    (2, 'AX', 'Islas Gland'), (3, 'AL', 'Albania'), (4, 'DE', 'Alemania'), (5, 'AD', 'Andorra'),
    (6, 'AO', 'Angola'), (7, 'AI', 'Anguilla'), (8, 'AQ', 'Antártida'), (9, 'AG', 'Antigua y Barbuda'),
    (10, 'AN', 'Antillas Holandesas'), (11, 'SA', 'Arabia Saudí'), (12, 'DZ', 'Argelia'), (13, 'AR', 'Argentina'),
    (14, 'AM', 'Armenia'), (15, 'AW', 'Aruba'), (16, 'AU', 'Australia'), (17, 'AT', 'Austria'),
    (18, 'AZ', 'Azerbaiyán'), (19, 'BS', 'Bahamas'), (20, 'BH', 'Bahréin'), (21, 'BD', 'Bangladesh'),
    (22, 'BB', 'Barbados'), (23, 'BY', 'Bielorrusia'), (24, 'BE', 'Bélgica'), (25, 'BZ', 'Belice'),
    (26, 'BJ', 'Benin'), (27, 'BM', 'Bermudas'), (28, 'BT', 'Bhután'), (29, 'BO', 'Bolivia'),
    (30, 'BA', 'Bosnia y Herzegovina'), (31, 'BW', 'Botsuana'), (32, 'BV', 'Isla Bouvet'), (33, 'BR', 'Brasil'),
    (34, 'BN', 'Brunéi'), (35, 'BG', 'Bulgaria'), (36, 'BF', 'Burkina Faso'), (37, 'BI', 'Burundi'),
    (38, 'CV', 'Cabo Verde'), (39, 'KY', 'Islas Caimán'), (40, 'KH', 'Camboya'), (41, 'CM', 'Camerún'),
    (42, 'CA', 'Canadá'), (43, 'CF', 'República Centroafricana'), (44, 'TD', 'Chad'), (45, 'CZ', 'República Checa'),
    (46, 'CL', 'Chile'), (47, 'CN', 'China'), (48, 'CY', 'Chipre'), (49, 'CX', 'Isla de Navidad'), (50, 'VA', 'Ciudad del Vaticano'),
    (51, 'CC', 'Islas Cocos'), (52, 'CO', 'Colombia'), (53, 'KM', 'Comoras'), (54, 'CD', 'República Democrática del Congo'),
    (55, 'CG', 'Congo'), (56, 'CK', 'Islas Cook'), (57, 'KP', 'Corea del Norte'), (58, 'KR', 'Corea del Sur'),
    (59, 'CI', 'Costa de Marfil'), (60, 'CR', 'Costa Rica'), (61, 'HR', 'Croacia'), (62, 'CU', 'Cuba'),
    (63, 'DK', 'Dinamarca'), (64, 'DM', 'Dominica'), (65, 'DO', 'República Dominicana'), (66, 'EC', 'Ecuador'),
    (67, 'EG', 'Egipto'), (68, 'SV', 'El Salvador'), (69, 'AE', 'Emiratos Árabes Unidos'), (70, 'ER', 'Eritrea'),
    (71, 'SK', 'Eslovaquia'), (72, 'SI', 'Eslovenia'), (73, 'ES', 'España'), (74, 'UM', 'Islas ultramarinas de Estados Unidos'), 
    (75, 'US', 'Estados Unidos'), (76, 'EE', 'Estonia'), (77, 'ET', 'Etiopía'), (78, 'FO', 'Islas Feroe'),
    (79, 'PH', 'Filipinas'), (80, 'FI', 'Finlandia'), (81, 'FJ', 'Fiyi'), (82, 'FR', 'Francia'),
    (83, 'GA', 'Gabón'), (84, 'GM', 'Gambia'), (85, 'GE', 'Georgia'), (86, 'GS', 'Islas Georgias del Sur y Sandwich del Sur'),
    (87, 'GH', 'Ghana'), (88, 'GI', 'Gibraltar'), (89, 'GD', 'Granada'), (90, 'GR', 'Grecia'),
    (91, 'GL', 'Groenlandia'), (92, 'GP', 'Guadalupe'), (93, 'GU', 'Guam'), (94, 'GT', 'Guatemala'),
    (95, 'GF', 'Guayana Francesa'), (96, 'GN', 'Guinea'), (97, 'GQ', 'Guinea Ecuatorial'), (98, 'GW', 'Guinea-Bissau'),
    (99, 'GY', 'Guyana'), (100, 'HT', 'Haití'), (101, 'HM', 'Islas Heard y McDonald'), (102, 'HN', 'Honduras'),
    (103, 'HK', 'Hong Kong'), (104, 'HU', 'Hungría'), (105, 'IN', 'India'), (106, 'ID', 'Indonesia'),
    (107, 'IR', 'Irán'), (108, 'IQ', 'Iraq'), (109, 'IE', 'Irlanda'), (110, 'IS', 'Islandia'),
    (111, 'IL', 'Israel'), (112, 'IT', 'Italia'), (113, 'JM', 'Jamaica'), (114, 'JP', 'Japón'),
    (115, 'JO', 'Jordania'), (116, 'KZ', 'Kazajstán'), (117, 'KE', 'Kenia'), (118, 'KG', 'Kirguistán'),
    (119, 'KI', 'Kiribati'), (120, 'KW', 'Kuwait'), (121, 'LA', 'Laos'), (122, 'LS', 'Lesotho'),
    (123, 'LV', 'Letonia'), (124, 'LB', 'Líbano'), (125, 'LR', 'Liberia'), (126, 'LY', 'Libia'),
    (127, 'LI', 'Liechtenstein'), (128, 'LT', 'Lituania'), (129, 'LU', 'Luxemburgo'), (130, 'MO', 'Macao'),
    (131, 'MK', 'ARY Macedonia'), (132, 'MG', 'Madagascar'), (133, 'MY', 'Malasia'), (134, 'MW', 'Malawi'),
    (135, 'MV', 'Maldivas'),  (136, 'ML', 'Malí'), (137, 'MT', 'Malta'), (138, 'FK', 'Islas Malvinas'),
    (139, 'MP', 'Islas Marianas del Norte'), (140, 'MA', 'Marruecos'), (141, 'MH', 'Islas Marshall'), (142, 'MQ', 'Martinica'),
    (143, 'MU', 'Mauricio'), (144, 'MR', 'Mauritania'), (145, 'YT', 'Mayotte'), (146, 'MX', 'México'),
    (147, 'FM', 'Micronesia'), (148, 'MD', 'Moldavia'), (149, 'MC', 'Mónaco'), (150, 'MN', 'Mongolia'),
    (151, 'MS', 'Montserrat'), (152, 'MZ', 'Mozambique'), (153, 'MM', 'Myanmar'), (154, 'NA', 'Namibia'),
    (155, 'NR', 'Nauru'), (156, 'NP', 'Nepal'), (157, 'NI', 'Nicaragua'), (158, 'NE', 'Níger'),
    (159, 'NG', 'Nigeria'), (160, 'NU', 'Niue'), (161, 'NF', 'Isla Norfolk'), (162, 'NO', 'Noruega'),
    (163, 'NC', 'Nueva Caledonia'), (164, 'NZ', 'Nueva Zelanda'), (165, 'OM', 'Omán'), (166, 'NL', 'Países Bajos'),
    (167, 'PK', 'Pakistán'), (168, 'PW', 'Palau'), (169, 'PS', 'Palestina'), (170, 'PA', 'Panamá'),
    (171, 'PG', 'Papúa Nueva Guinea'), (172, 'PY', 'Paraguay'), (173, 'PE', 'Perú'), (174, 'PN', 'Islas Pitcairn'),
    (175, 'PF', 'Polinesia Francesa'), (176, 'PL', 'Polonia'), (177, 'PT', 'Portugal'), (178, 'PR', 'Puerto Rico'),
    (179, 'QA', 'Qatar'), (180, 'GB', 'Reino Unido'), (181, 'RE', 'Reunión'), (182, 'RW', 'Ruanda'),
    (183, 'RO', 'Rumania'), (184, 'RU', 'Rusia'), (185, 'EH', 'Sahara Occidental'), (186, 'SB', 'Islas Salomón'),
    (187, 'WS', 'Samoa'), (188, 'AS', 'Samoa Americana'), (189, 'KN', 'San Cristóbal y Nevis'), (190, 'SM', 'San Marino'),
    (191, 'PM', 'San Pedro y Miquelón'), (192, 'VC', 'San Vicente y las Granadinas'), (193, 'SH', 'Santa Helena'),
    (194, 'LC', 'Santa Lucía'), (195, 'ST', 'Santo Tomé y Príncipe'), (196, 'SN', 'Senegal'), (197, 'CS', 'Serbia y Montenegro'),
    (198, 'SC', 'Seychelles'), (199, 'SL', 'Sierra Leona'), (200, 'SG', 'Singapur'), (201, 'SY', 'Siria'),
    (202, 'SO', 'Somalia'), (203, 'LK', 'Sri Lanka'), (204, 'SZ', 'Suazilandia'), (205, 'ZA', 'Sudáfrica'),
    (206, 'SD', 'Sudán'), (207, 'SE', 'Suecia'), (208, 'CH', 'Suiza'), (209, 'SR', 'Surinam'),
    (210, 'SJ', 'Svalbard y Jan Mayen'), (211, 'TH', 'Tailandia'), (212, 'TW', 'Taiwán'), (213, 'TZ', 'Tanzania'),
    (214, 'TJ', 'Tayikistán'), (215, 'IO', 'Territorio Británico del Océano Índico'), (216, 'TF', 'Territorios Australes Franceses'),
    (217, 'TL', 'Timor Oriental'), (218, 'TG', 'Togo'), (219, 'TK', 'Tokelau'), (220, 'TO', 'Tonga'),
    (221, 'TT', 'Trinidad y Tobago'), (222, 'TN', 'Túnez'), (223, 'TC', 'Islas Turcas y Caicos'),
    (224, 'TM', 'Turkmenistán'), (225, 'TR', 'Turquía'), (226, 'TV', 'Tuvalu'), (227, 'UA', 'Ucrania'),
    (228, 'UG', 'Uganda'), (229, 'UY', 'Uruguay'), (230, 'UZ', 'Uzbekistán'), (231, 'VU', 'Vanuatu'),
    (232, 'VE', 'Venezuela'), (233, 'VN', 'Vietnam'), (234, 'VG', 'Islas Vírgenes Británicas'), 
    (235, 'VI', 'Islas Vírgenes de los Estados Unidos'), (236, 'WF', 'Wallis y Futuna'), (237, 'YE', 'Yemen'),
    (238, 'DJ', 'Yibuti'), (239, 'ZM', 'Zambia'), (240, 'ZW', 'Zimbabue');
    -- DATOS DE LA TABLA DE MATERIALES
    insert into proyectobox.materiales (nombre, descripcion, precio, imagen, corte, cantidad, origen) values
    ('Cuarzo Rosado', 'designa a dos variedades del cuarzo que tienen el mism color, pero cuyo aspecto, aplicaciones y sobre todo origen del color es distinto.', 2000.00, 'Cuarzo Rosa.jfif', 'REDONDO', 2, 1),
    ('Amatista', 'Es una variedad macrocristalina violeta del cuarzo. El color puede ser más o menos intenso, según la cantidad de hierro que contenga. Puede presentarse coloreada por zonas con cuarzo transparente o amarillo. Las puntas suelen ser más oscuras o degradarse hasta el cuarzo incoloro.', 3000.00, 'Amatista.jfif','COJIN', 2, 2),
    ('Howlite', 'Ambién llamada khaulita o silicoborocalcita, es un mineral de la clase de los minerales boratos según la 10.ª clasificación de Strunz.', 3500.00, 'Howlita.jfif', 'PRINCESA', 6, 3),
    ('Onix', 'Es un mineral de la clase 4; según la clasificación de Strunz es considerado como piedra semipreciosa, ​ aunque según la Asociación Mineralógica Internacional no es aceptado como mineral sino como una variedad de ágata o calcedonia. Está compuesto de sílice.',3000.00, 'Onix.jfif', 'OVALO', 8, 4),
    ('Jade', 'Es una roca ornamental. El término jade es aplicado a dos rocas metamórficas distintas compuestas de diferentes minerales silicatados: La nefrita consiste en un agregado de fibras entrelazadas microcristalinas de calcio, mineral anfíbol rico en magnesio-hierro de la serie de la tremolita-ferroactinolita.' ,5000.00, 'Jade.jfif', 'RADIANTE', 5, 10),
    ('Ágata', 'No es un mineral específico, sino un conjunto de variedades microcristalinas del cuarzo. En realidad, son variedades de calcedonia que presentan bandas de varios colores poco contrastados.', 4200.00, 'Agata.jpg', 'ESMERALDA', 4, 16),
    ('Aventurina', 'Se caracteriza por la presencia de ciertas inclusiones, que le dan su color y que provocan unos reflejos brillantes especiales conocidos como efecto aventurinado.', 3500.00, 'Aventurina.jpg', 'CORAZON', 6, 20),
    ('Vulcanica', 'Es una piedra muy porosa , altamente absorbente e ideal para usar como collar de aromaterapia y en diferentes detalles en accesorios.​', 3000.00, 'Vulcanica.jfif', 'ASHER', 9, 35),
    ('Ópalo', 'Es un mineraloide del grupo IX, según la clasificación de Strunz. Tiene una composición similar a la del cuarzo del que se diferencia porque tiene moléculas de agua en su interior.', 2500.00, 'Opalo.jfif', 'PERA', 10, 69),
    ('Cuarzo Cristal', 'El cuarzo blanco o transparente es un mineral compuesto por dióxido de sílice perteneciente a la variedad macrocristalina, el cual debe su color a que posee burbujas de aire en su estructura, de manera que son cristales de caras hexagonales.', 3000.00, 'Cuarzo Cristal.jfif', 'MARQUESA', 5, 102),
    ('Pirita', 'La pirita se presenta en numerosas formas y hábitos. Los agregados de cristales más pequeños pueden desprender un hermoso efecto de brillo en la luz, y los cristales más grandes pueden estar perfectamente formados, incluidos los fascinantes cubos , la penetración de gemelos y otras formas de cristales interesantes.', 4300.00, 'Pirita.jfif', 'REDONDO', 0, 105),
    ('Obsidiana', 'Llamada a veces vidrio volcánico, es un tipo de roca ígnea —roca volcánica perteneciente al grupo de los silicatos—, con una composición química de silicatos alumínicos y un gran porcentaje de óxidos silícicos. Su composición es parecida al granito y la riolita.', 4000.00, 'Obsidiana.jfif', 'COJIN', 5, 109),
    ('Jaspe', 'Es una roca sedimentaria. Posee una superficie suave y se utiliza para ornamentación o como gema. Se puede pulir y utilizar en floreros, sellos y, tiempo atrás se la utilizó para cajas de tabaco.', 3600.00, 'Jaspe.jfif', 'PRINCESA', 4, 145),
    ('Amazonita', 'Es la escasa variedad verde de la microclina, un mineral del grupo de los feldespatos. Durante muchos años se pensó que su color se debía al cobre ya que los compuestos de este metal suelen ser verdes o azules.', 3800.00, 'Amazonita.jfif', 'OVALO', 9, 160),
    ('Jade Rojo', 'Consiste en uno de los minerales exóticos más destacados y valiosos del planeta. Es una variedad de jade con una tonalidad intensa parecida a la sangre. Se distingue de otros minerales similares por tener una mayor densidad y dureza.', 4100.00, 'Jade Rojo.jpg', 'RADIANTE', 8, 165),
    ('Hilo Elástico', 'Hilo de cuentas elástica de color blanco de 50m por rollo, de aprox. 1 mm de ancho y 0,5 mm de espesor.', 200.00, 'Hilo Elastico.jpg', NULL, 9, 13),
    ('Hilo chino', 'Hilos chinos de colores intenso para tejer bisutería manualidades joyas joyeria de 100 metros cada rollo.', 200.00, 'Hilo Chino.jpg', NULL, 8, 47),
    ('Yesquero', 'Cómodos y prácticos, se recargan con benzina, de material liso y con relieves de figuras. ', 50.00, 'Yesquero.jfif', NULL, 6, 100);
    
    -- DATOS DE LA TABLA DE PRODUCTOS
    insert into proyectobox.productos (nombre,precio,categoria,cantidad,imagen) values
    ('Collar de Bisutería de Piedra de Ágata', 15000, 'COLLAR', 3, 'Collar de Bisutería de Piedra de Agata.jpg'), 
    ('Agata Ruiz de la Prada', 9000, 'ANILLO', 2, 'Agata Ruiz de la Prada.jpg'),
    ('Pulsera de Plata con Agata Azul Turquesa', 12000, 'PULSERA', 3, 'Pulsera de Plata con Agata Azul Turquesa.jpg'),
    ('Anillo de Plata con Amatista', 10000, 'ANILLO', 3, 'Anillo de Plata con Amatista.jpg'),
    ('Aretes de Diamantes con Amatista', 19000, 'ARETES', 4, 'Aretes de Diamantes con Amatista.jpg'),
    ('PULSERA de Energia con Piedras de Amazonita', 12000, 'PULSERA', 2, 'Pulsera de Energia con Piedras de Amazonita.jfif'),
    ('Anillo de Plata y Piedra de Aventurina', 10000, 'ANILLO', 2, 'Anillo de Plata y Piedra de Aventurina.jfif'),
    ('Collares Simple de Cuarzo Cristal', 8000, 'COLLAR', 2, 'Collares Simple de Cuarzo Cristal.jfif'),
    ('Collar Pulido de Cuarzo Cristal', 8500, 'COLLAR', 3, 'Collar Pulido de Cuarzo Cristal.jfif'),
    ('Collar Lunar de Cuarzo Rosado', 9800, 'COLLAR', 1, 'Collar Lunar de Cuarzo Rosado.jfif'),
    ('Aretes Simples de Cuarzo Rosado', 10500, 'ARETES', 0, 'Aretes Simples de Cuarzo Rosado.jfif'),
    ('Collar de Perlas Estilo Howlite', 12000, 'COLLAR', 4, 'Collar de Perlas Estilo Howlite.jfif'),
    ('Aretes de Perlas de Howlite', 9000, 'ARETES', 6, 'Aretes de Perlas de Howlite.jfif'),
    ('Anillo de Jade Rojo Pulido', 10500, 'ANILLO', 1, 'Anillo de Jade Rojo Pulido.jfif'),
    ('Aretes de Jade Estilo Aztecas', 12000, 'ARETES', 2, 'Aretes de Jade Estilo Aztecas.jfif'),
    ('Tiara Estilo Quing con Incrustaciones de Jade', 21000, 'TIARA', 2, 'Tiara Estilo Quing con Incrustaciones de Jade.jpg'),
    ('Anillo de Plata con Incrustaciones con Jaspe', 12000, 'ANILLO', 2, 'Anillo de Plata con Incrustaciones con Jaspe.jfif'),
    ('PULSERA de Obsidiana Pulida', 18000, 'PULSERA', 3, 'Pulsera de Obsidiana Pulida.jfif'),
    ('Tiara de Plata con Incrustaciones de Obsidiana', 25000, 'TIARA', 3, 'Tiara de Plata con Incrustaciones de Obsidiana.jpg'),
    ('Aretes de Plata con Onix Pulido', 14000, 'ARETES', 3, 'Aretes de Plata con Onix Pulido.jfif'),
    ('Anillo de Plata con Piedra de Onix', 11500, 'ANILLO', 3, 'Anillo de Plata con Piedra de Onix.jpg'),
    ('Anillo con Opalo Pulido', 9500, 'ANILLO', 4, 'Anillo con Opalo Pulido.jfif'),
    ('Collar de Cadena con Opalo Pulido Circular', 12500, 'COLLAR', 1, 'Collar de Cadena con Opalo Pulido Circular.jpg'),
    ('Tiara Estilo Quing con Incrustaciones de Opalo', 23000, 'TIARA', 0, 'Tiara Estilo Quing con Incrustaciones de Opalo.jfif'),
    ('Collar de Cadena con Pirita Cortada', 12000, 'COLLAR', 0, 'Collar de Cadena con Pirita Cortada.jfif'),
    ('Anillo de Plata con Pirita', 9000, 'ANILLO', 1, 'Anillo de Plata con Pirita.jfif'),
    ('PULSERA de Cupido de Vulcanita', 12000, 'PULSERA', 0, 'Pulsera de Cupido de Vulcanita.jfif');
    -- DATOS DE LA TABLA DE PRODCUTOS Y SUS PIEDRAS
    insert into proyectobox.p_m values 
    (1,24), (1,35), (2,24), (3,24), (4,20), (5,20), (5,34), (6,32), (6,35), (7,25), (8,28), (8,34), (9,28), (9,35), (10,19), (10,35), (11,19), (11,34),
    (12,21), (12,34), (13,21), (14,33), (15,23), (16,23), (17,31), (18,30), (18,35), (19,30), (20,22), (21,22), (22,27), (23,27), (24,27), (25,29), (26,29), (27,26), (27,35);